name: ecommerce
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'







dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  carousel_slider: ^5.0.0
  http: ^1.2.2
  logger: ^2.5.0
  provider: ^6.1.2
  flutter_rating: ^2.0.2
  shared_preferences: ^2.2.3
  flutter_native_splash: ^2.4.0
  get: ^4.6.6
  webview_flutter: ^4.8.0
  freezed: ^2.5.2
  sembast: ^3.7.1
  path_provider: ^2.1.4
  cached_network_image: ^3.4.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9





flutter:
  assets:
    - assets/images/cat_1.png
    - assets/images/cat_2.png
    - assets/images/cat_3.png
    - assets/images/cat_4.png
    - assets/images/cat_5.png
    - assets/images/cat_6.png
    - assets/images/company_logo.png
    - assets/auth/img_1.png
    - assets/auth/img2.png
    - assets/payment/googlePay.png
    - assets/payment/paytm.png
    - assets/payment/phonepe.png



  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
