name: ecommerce
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.6
  carousel_slider: ^5.0.0
  http: ^1.2.2
  logger: ^2.5.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^3.0.0





flutter:
  assets:
    - assets/images/img.png
    - assets/images/img_1.png
    - assets/images/img_2.png
    - assets/images/img_3.png
    - assets/images/img_4.png
    - assets/images/cat_1.png
    - assets/images/cat_2.png
    - assets/images/cat_3.png
    - assets/images/cat_4.png
    - assets/images/cat_5.png
    - assets/images/cat_6.png
    - assets/images/company_logo.png


  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
