name: Release build on tag push
on:
  push:
    branches:
      - "feat/ci_cd"
    tags:
      - "v*.*.*"
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: actions/setup-java@v3.0.0
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2.3.0
        with:
          channel: 'stable'
          flutter-version: '3.19.6'

      - name: 'Flutter Doctor'
        run: flutter doctor -v

      - name: 'Remove pubspec.lock file'
        uses: JesseTG/rm@v1.0.3
        with:
          path: pubspec.lock

      - name: 'Flutter Clean'
        run: flutter clean

      - name: 'Flutter Pub Get'
        run: flutter pub get

      - name: 'Build Debug Apk'
        run: flutter build apk  --release --split-per-abi

      - name: "Post APK To Slack"
        id: pingSlack
        uses: FieldAssist/slack-share@v0.1.5
        with:
          SLACK_TOKEN: ${{ secrets.TOKEN }}
          SLACK_CHANNEL: 'D087DAZRC2F'
          SHARE_FILE: true
          FILE_PATH: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
          SLACK_MESSAGE: |
            Trigger by: @${{ github.actor }}